### ISSUE TITLE
Add regional rail stations to the viz

### ISSUE THREAD

**Issue by mjumbewu** [mjumbewu/phillytranspo_art#1]
These should maybe be displayed in the same way as the subway lines for now. This would involve, at a high level:
- pulling the rail GTFS files out of SEPTA's zip file (http://www2.septa.org/developer/)
- running the `mksubways` script on the regional rail data
- adding the resulting JSON files for display in the visualization

**Comment by johnsons531** [comment]
created regional rail data by replicating and modifying the mksubways.py script. didn't send a pull request in case mentees want to try on their own. https://github.com/johnsons531/phillytranspo_art/commits/gh-pages

**Comment by johnsons531** [comment]
regional rail is visualized with a unique shape with transitions
